spring.application.name=resumeanalyzer


### Open API ###
openapi-prompt=Extract name, email, phone, skills, location, Experience details from the following resume and provide in standard JSON response
apenapi-key=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