spring.application.name=resumeanalyzer


### Open API ###
openapi-prompt=Extract name, email, phone, skills, location, Experience details from the following resume and provide in standard JSON response
openapi-key=